### ISSUE TITLE
The stream view buttons are very broken.

### ISSUE THREAD

**Issue by forkiesassds** [XYZenix/DTM-16#1]
This might've broken with a discord or theme update as the stream view buttons are very broken.
![image](https://user-images.githubusercontent.com/54495659/109427453-2d60c180-79fb-11eb-8599-1651b281bd2a.png)

**Comment by XYZenix** [comment]
the call ui is always broken...i barely use vc and there's always something broken with those buttons, i'll figure something out

**Comment by XYZenix** [comment]
ok should probably be fixed? seems to work fine here, unless something else is broken that i'm confused about
![image](https://user-images.githubusercontent.com/51988432/109430582-cba85380-7a0a-11eb-93d1-e395ca27e868.png)
