### ISSUE TITLE
No seperator above replies

### ISSUE THREAD

**Issue by Diyamund** [XYZenix/DTM-16#2]
There is no seperator above replies.
![image](https://user-images.githubusercontent.com/44238627/121750794-ab406880-cad2-11eb-9d70-80cd7abc98d8.png)

**Comment by XYZenix** [comment]
it's not a problem with replies, it's a problem with mentions, fixed in dtm-16 build 132  (XYZenix/XYZenixThemes@b436f9605b18c2ad0a4edd385b4a73001df93e7a)
