### ISSUE TITLE
discord home button still shows new logo

### ISSUE THREAD

**Issue by DodoGames7** [XYZenix/DTM-16#7]
when you use DTM 16 Theme with stylus the home is still discord's new logo
![image](https://user-images.githubusercontent.com/69091682/139158372-5cc4629c-9c2d-4551-b160-c3f322d2c9ce.png)

i dont know if a new discord update broke the theme or something, not sure if lts only for me or for everyone

**Comment by XYZenix** [comment]
should be fixed (XYZenix/XYZenixThemes@4a5d9c403f41dd7bff071c557766b715db01ff65)
