### ISSUE TITLE
group chats still use the new icon when they're not supposed to

### ISSUE THREAD

**Issue by peepee** [XYZenix/DTM-16#9]
this claimed to be added in https://github.com/XYZenix/DTM-16/issues/3#issuecomment-885162946 but it doesn't seem to work.
![image](https://user-images.githubusercontent.com/49787675/139749805-b4ab2bde-bebe-4413-b826-fe55cf2d191d.png)

**Comment by XYZenix** [comment]
should be done in XYZenix/XYZenixThemes@4a5d9c403f41dd7bff071c557766b715db01ff65
